version: 0.1

phases:
  install:
    commands:
      - yum install python3 -y
  pre_build:
    commands:
      - ls
      - python3 -m venv .venv --prompt .
  build:
    commands:
      - source .venv/bin/activate
      - pip install --upgrade pip wheel
      - pip install -r requirements.txt
      - pip install git+https://github.com/taigaio/taiga-contrib-protected.git@6.0.0#egg=taiga-contrib-protected
      - ls settings
artifacts:
  files:
    - '**/*'
